version: '2'
services:
    # API
    api:
        build: '.'
        command: 'python manage.py runserver 0.0.0.0:8000'
        volumes:
            - './api:/src'
            - './.data:/data'
        env_file: './api/.env'
        environment:
            DEBUG: 'True'
        ports:
            - '80:8000'
    # Development watch & compile
    ui:
        build: './ui'
        command: ['npm', 'start']
        volumes:
            - './ui:/app'
            - './api:/api'
            - '/app/node_modules'

