version: '2'
services:
    # API
    api:
        build: '.'
        command: 'python manage.py runserver 0.0.0.0:8000'
        volumes:
            - './api:/api'
            - './.data:/data'
        env_file: './api/.env'
        ports:
            - '8000:8000'
        environment:
            DEBUG: 'True'
    # Development watch & compile
    ui:
        build: './ui'
        command: ['npm', 'start']
        volumes:
            - './ui:/ui'
            - '/ui/node_modules'
        ports:
            - '80:3000'
        links:
            - 'api'
