version: '3'
services:
    # API
    api:
        build: '.'
        command: 'python manage.py runserver 0.0.0.0:8000'
        volumes:
            - './api:/src'
            - './.data:/data'
            - './.public:/public'
        env_file: './api/.env'
        ports:
            - '8000:8000'
        environment:
            DEBUG: 'True'
    # Development watch & compile
    ui:
        build: './ui'
        command: ['npm', 'start']
        stdin_open: true
        volumes:
            - './ui:/ui'
            - '/ui/node_modules'
        ports:
            # Using "80:3000" throws weird "RSV1 must be clear" websocket errors
            - '8100:3000'
        links:
            - 'api'
