ingredient_categories = [
    (1, 'Uncategorized'),
    (2, 'Bitters'),
    (3, 'Syrup'),
    (4, 'Juice'),
    (5, 'Kitchen Staples'),
    (6, 'Gin'),
    (7, 'Rum'),
    (8, 'Tequila'),
    (9, 'Brandy'),
    (10, 'Whisk(e)y'),
    (11, 'Sherry & Port'),
    (12, 'Vermouth'),
    (13, 'Beer & Wine'),
    (14, 'Amaro & Apertivos'),
    (15, 'Liqueur & Cordials'),
    (16, 'Other Spirits'),
]

# (regex pattern, generic, category) in order of preference
base_substitutions = [
    ('blackstrap rum', 'Blackstrap Rum', 'Rum'),
    ('(white|clear|silver) rum', 'White Rum', 'Rum'),
    ('(amb(er|re)|gold(en)?|pale) rum', 'Amber Rum', 'Rum'),
    ('(dark|black) rum', 'Dark Rum', 'Rum'),
    ('navy (strength )? rum', 'Navy Rum', 'Rum'),
    ('(aged|year|vintage) rum', 'Aged Rum', 'Rum'),
    ('overproof rum', 'Overproof Rum', 'Rum'),
    ('cachaca', 'Cachaça', 'Rum'),
    ('aguardiente', 'Aguardiente', 'Rum'),
    ('agricole', 'Rhum', 'Rum'),
    ('spiced rum', 'Spiced Rum', 'Rum'),
    ('old tom gin', 'Old Tom Gin', 'Gin'),
    ('(g|j)enev(er|a)', 'Genever', 'Gin'),
    ('genevieve gin', 'Genever', 'Gin'),
    ('peket', 'Genever', 'Gin'),
    ('apple brandy', 'Apple Brandy', 'Brandy'),
    ('calvados', 'Apple Brandy', 'Brandy'),
    ('applejack', 'Apple Brandy', 'Brandy'),
    ('armagnac', 'Armagnac', 'Brandy'),
    ('cognac', 'Cognac', 'Brandy'),
    ('pisco', 'Pisco', 'Brandy'),
    ('brandy', 'Brandy', 'Brandy'),
    ('japanese whiskey', 'Japanese Whisky', 'Whisk(e)y'),
    ('irish whiskey', 'Irish Whiskey', 'Whisk(e)y'),
    ('(white|silver|blanco) tequila', 'White Tequila', 'Tequila'),
    ('reposado tequila', 'Reposado Tequila', 'Tequila'),
    ('anejo tequila', 'Añejo Tequila', 'Tequila'),
    ('porto?$', 'Port', 'Sherry & Port'),
    ('sherry', 'Sherry', 'Sherry & Port'),
    ('madeira', 'Madeira', 'Sherry & Port'),
    ('marsala', 'Marsala', 'Sherry & Port'),
    ('(quin)?quina', 'Quina', 'Amaro & Apertivos'),
    ('kina', 'Quina', 'Amaro & Apertivos'),
    ('(sweet|red|italian|rose) vermouth', 'Sweet Vermouth', 'Vermouth'),
    ('(white|bianco|blanco) vermouth', 'White Vermouth', 'Vermouth'),
    ('dry vermouth', 'Dry Vermouth', 'Vermouth'),
    ('arrack', 'Arrack', 'Other Spirits'),
    ('becherovka', 'Becherovka', 'Other Spirits'),
    ('absinthe', 'Absinthe', 'Other Spirits'),
    ('orgeat', 'Orgeat', 'Liqueur & Cordials'),
    ('curacao', 'Curaçao', 'Liqueur & Cordials'),
    ('falernum', 'Falernum', 'Liqueur & Cordials'),
    ('orange bitters', 'Orange Bitters', 'Bitters'),
    # Very Generic
    ('tequila', 'Tequila', 'Tequila'),
    ('mezcal', 'Mezcal', 'Tequila'),
    ('scotch', 'Scotch', 'Whisk(e)y'),
    ('bourbon', 'Bourbon', 'Whisk(e)y'),
    ('rye', 'Rye', 'Whisk(e)y'),
    ('whiskey', 'Whiskey', 'Whisk(e)y'),
    ('whisky', 'Whisky', 'Whisk(e)y'),
    ('vermouth', 'Vermouth', 'Vermouth'),
    ('rhum', 'Rhum', 'Rum'),
    ('rum', 'Rum', 'Rum'),
    ('gin', 'Gin', 'Gin'),
    ('vodka', 'Vodka', 'Other Spirits'),
    ('ginger (beer|ale)', None, 'Kitchen Staples'),
    # Wine & Beer
    ('beer', 'Beer', 'Beer & Wine'),
    ('ale', 'Beer', 'Beer & Wine'),
    ('stout', 'Beer', 'Beer & Wine'),
    ('porter', 'Beer', 'Beer & Wine'),
    ('lager', 'Beer', 'Beer & Wine'),
    ('ipa', 'Beer', 'Beer & Wine'),
    ('sparkling wine', 'Sparkling Wine', 'Beer & Wine'),
    ('champagne', 'Sparkling Wine', 'Beer & Wine'),
    ('brut', 'Sparkling Wine', 'Beer & Wine'),
    ('cava', 'Sparkline Wine', 'Beer & Wine'),
    ('prosecco', 'Sparkling Wine', 'Beer & Wine'),
    ('wine', 'Wine', 'Beer & Wine'),
    # Categories Only
    ('liqueur', None, 'Liqueur & Cordials'),
    ('cordial', None, 'Liqueur & Cordials'),
    ('creme de', None, 'Liqueur & Cordials'),
    ('honey', None, 'Kitchen Staples'),
    ('soda', None, 'Kitchen Staples'),
    ('(leaf|leaves)', None, 'Kitchen Staples'),
    ('vinegar', None, 'Kitchen Staples'),
    ('sauce', None, 'Kitchen Staples'),
    ('cube(s)', None, 'Kitchen Staples'),
    ('slice(d)', None, 'Kitchen Staples'),
    ('tonic', None, 'Kitchen Staples'),
    ('bitters', None, 'Bitters'),
    ('syrup', None, 'Syrup'),
    ('shrubb?', None, 'Syrup'),
    ('juice', None, 'Juice'),
    ('amaro', None, 'Amaro & Apertivos'),
    ('fernet', None, 'Amaro & Apertivos'),
    ('aperti(f|vo|v)', None, 'Amaro & Apertivos'),
    ('digesti(f|vo|v)', None, 'Amaro & Apertivos'),
]
