base_substitutions = {
    'rum': 'Rum',
    'rhum': 'Rum',
    'tequila': 'Tequila',
    'mezcal': 'Mezcal',
    'gin': 'Gin',
    'brandy': 'Brandy',
    'cognac': 'Cognac',
    'rye': 'Rye',
    'scotch': 'Scotch',
    'bourbon': 'Bourbon',
    'sherry': 'Sherry',
    'sweet vermouth': 'Sweet Vermouth',
    'dry vermouth': 'Dry Vermouth',
}
