# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(0, ''), (1, 'oz'), (2, 'dash'), (3, 'barspoon'), (4, 'pinch'), (5, 'teaspoon'), (6, 'tablespoon'), (7, 'sprig'), (8, 'leaf'), (9, 'spritz')], null=True),
        ),
    ]
