# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-13 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_auto_20181010_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
