# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0004_auto_20181010_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='substitutions',
            field=models.ManyToManyField(blank=True, to='drinks.Ingredient'),
        ),
    ]
