# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0004_auto_20181014_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Booze'), (2, 'Bitters'), (3, 'Syrup'), (4, 'Juice'), (5, 'Kitchen Staples')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='generic',
            field=models.BooleanField(default=False),
        ),
    ]
