# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0005_auto_20181024_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
