# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-14 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0009_auto_20190309_2115'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-created'], name='drinks_comm_created_bb25d2_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['-created'], name='drinks_reci_created_d0775e_idx'),
        ),
        migrations.AddIndex(
            model_name='userfavorite',
            index=models.Index(fields=['-created'], name='drinks_user_created_0310aa_idx'),
        ),
    ]
