# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 17:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone



def favorites_to_lists(apps, schema_editor):
    """
    We're going to drop Favorites, so load user favorites into a new list
    """
    UserFavorite = apps.get_model('drinks', 'UserFavorite')
    UserList = apps.get_model('drinks', 'UserList')
    UserListRecipe = apps.get_model('drinks', 'UserListRecipe')

    lists = {}
    for fav in UserFavorite.objects.iterator():
        if not lists.get(fav.user.id):
            lists[fav.user.id] = []
        lists[fav.user.id].append(fav.recipe.id)

    for user_id, recipes in lists.items():
        l = UserList(
            user_id=user_id,
            name='Favorites'
        )
        l.save()
        for index, r_id in enumerate(recipes):
            UserListRecipe(
                recipe_id=r_id,
                user_list=l,
                order=index
            ).save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drinks', '0011_tag_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserListRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('order', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='updated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('user', 'recipe')]),
        ),
        migrations.AlterUniqueTogether(
            name='useringredient',
            unique_together=set([('user', 'ingredient')]),
        ),
        migrations.AddField(
            model_name='userlistrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinks.Recipe'),
        ),
        migrations.AddField(
            model_name='userlistrecipe',
            name='user_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinks.UserList'),
        ),
        migrations.AddField(
            model_name='userlist',
            name='recipes',
            field=models.ManyToManyField(through='drinks.UserListRecipe', to='drinks.Recipe'),
        ),
        migrations.AddField(
            model_name='userlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userlistrecipe',
            index=models.Index(fields=['-created'], name='drinks_user_created_2b7a08_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userlistrecipe',
            unique_together=set([('recipe', 'user_list')]),
        ),
        migrations.AddIndex(
            model_name='userlist',
            index=models.Index(fields=['-created'], name='drinks_user_created_fa6dcd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userlist',
            unique_together=set([('name', 'user')]),
        ),
        migrations.RunPython(favorites_to_lists),
        migrations.RemoveField(
            model_name='userfavorite',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='userfavorite',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserFavorite',
        ),
    ]
