# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 14:17
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.text import slugify
import django.db.models.deletion


def create_slugs(apps, schema_editor):
    """
    Fill in recipe slug values
    """
    Recipe = apps.get_model('drinks', 'Recipe')
    slugs = set()
    for r in Recipe.objects.iterator():
        slug = slugify(r.name)
        if slug.isdigit():
            slug = '_%s' % slug
        uslug = slug
        num = 0
        while uslug in slugs:
            num += 1
            uslug = '%s-%d' % (slug, num)
        slugs.add(uslug)
        r.slug = uslug
        r.save()


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0012_auto_20190319_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, null=True, default=None),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='userlistrecipe',
            name='user_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='drinks.UserList'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['name'], name='drinks_reci_name_15bbf0_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['slug'], name='drinks_reci_slug_50adce_idx'),
        ),
        migrations.RunPython(create_slugs),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
