# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 22:58
from __future__ import unicode_literals

from django.utils.timezone import now
from django.db import migrations, models
import django.db.models.deletion


UNIT_MAP = dict([
    (0, ''),
    (1, 'oz'),
    (2, 'dash'),
    (3, 'barspoon'),
    (4, 'pinch'),
    (5, 'teaspoon'),
    (6, 'tablespoon'),
    (7, 'sprig'),
    (8, 'leaf'),
    (9, 'spritz'),
    (10, 'wedge'),
])

global QUANTITY_MAP
QUANTITY_MAP = dict()


# This load-into-memory, write-out-of-memory approach kinda stinks, but renaming
# the old column and writing from that column to the new one didn't see to work.

def pull_units(apps, schema_editor):
    """
    Create the UOMs and load them into memory
    """
    Uom = apps.get_model('drinks', 'Uom')
    for unit in UNIT_MAP.values():
        Uom(name=unit).save()
    Quantity = apps.get_model('drinks', 'Quantity')
    for quantity in Quantity.objects.iterator():
        QUANTITY_MAP[quantity.id] = UNIT_MAP[quantity.unit]


def write_units(apps, schema_editor):
    """
    Write UOMs out of memory onto quantities
    """
    Uom = apps.get_model('drinks', 'Uom')
    Quantity = apps.get_model('drinks', 'Quantity')
    for quantity in Quantity.objects.iterator():
        quantity.unit = Uom(name=QUANTITY_MAP[quantity.id])
        quantity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0013_auto_20190327_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uom',
            fields=[
                ('name', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RunPython(pull_units),
        migrations.AlterField(
            model_name='quantity',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinks.Uom'),
        ),
        migrations.RunPython(write_units),
    ]

