# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


UNIT_MAP = dict([
    (0, ''),
    (1, 'oz'),
    (2, 'dash'),
    (3, 'barspoon'),
    (4, 'pinch'),
    (5, 'teaspoon'),
    (6, 'tablespoon'),
    (7, 'sprig'),
    (8, 'leaf'),
    (9, 'spritz'),
    (10, 'wedge'),
])


def migrate_units(apps, schema_editor):
    """
    Migrate the UOM from old enum to new table
    """
    Uom = apps.get_model('drinks', 'Uom')
    for unit in UNIT_MAP.values():
        Uom(name=unit).save()
    Quantity = apps.get_model('drinks', 'Quantity')
    for quantity in Quantity.objects.iterator():
        quantity.unit_name = UNIT_MAP[quantity.unit_old]
        quantity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0013_auto_20190327_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('name', models.CharField(max_length=36, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField('Quantity', 'unit', 'unit_old'),
        migrations.AddField(
            model_name='quantity',
            name='unit',
            field=models.ForeignKey(
                default='oz',
                on_delete=django.db.models.deletion.CASCADE,
                to='drinks.Uom'
            ),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_units),
        migrations.RemoveField(model_name='quantity', name='unit_old'),
    ]
