# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-29 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0014_auto_20190327_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uom',
            options={
                'verbose_name': 'unit of measure',
                'verbose_name_plural': 'units of measure'
            },
        ),
    ]
