# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0014_auto_20190327_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='unit',
            field=models.ForeignKey(default='oz', on_delete=django.db.models.deletion.CASCADE, to='drinks.Uom'),
        ),
    ]
