# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-09 23:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def create_default_block(apps, schema_editor):
    Block = apps.get_model('drinks', 'Block')
    rb = Block(
        name='Public Recipes',
        public=True
    )
    rb.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drinks', '0015_auto_20190329_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('public', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlockUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.BooleanField(default=False)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinks.Block')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='Block',
            name='users',
            field=models.ManyToManyField(related_name='blocks', through='drinks.BlockUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(create_default_block),
        migrations.AddField(
            model_name='recipe',
            name='block',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drinks.Block'),
            preserve_default=False,
        ),
    ]
