# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-04 12:54
from __future__ import unicode_literals

from django.db import migrations, models

def move_urls(apps, schema_editor):
    Recipe = apps.get_model('drinks', 'Recipe')
    for r in Recipe.objects.filter(source__startswith='http').iterator():
        r.url = r.source
        r.source = r.url.split('/')[2]
        r.save()


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0016_auto_20190709_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(move_urls),
    ]
