# Generated by Django 3.0 on 2020-06-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0020_profile_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('name', 'book')},
        ),
    ]
