# Generated by Django 3.0 on 2020-07-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0021_auto_20200616_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Uncategorized'), (2, 'Bitters'), (3, 'Syrup'), (4, 'Juice'), (5, 'Kitchen Staples'), (6, 'Gin'), (7, 'Rum'), (8, 'Tequila'), (9, 'Brandy'), (10, 'Whisk(e)y'), (11, 'Sherry & Port'), (12, 'Vermouth'), (13, 'Beer & Wine'), (14, 'Amaro & Apertivos'), (15, 'Liqueur & Cordials'), (16, 'Other Spirits')], default=1, null=True),
        ),
    ]
