# Generated by Django 3.0 on 2020-07-28 07:27

from django.db import migrations
import os

fn = os.path.join(os.path.dirname(__file__), './sql/activity-view.sql')
with open(fn, 'r') as f:
    raw_sql = f.read()


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0023_auto_20200704_1557'),
    ]

    operations = [
        migrations.RunSQL(
            raw_sql,
            reverse_sql='DROP VIEW IF EXISTS drinks_activity'
        )
    ]
