# Generated by Django 3.0 on 2021-01-08 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0024_auto_20200728_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('body', models.TextField(null=True)),
                ('type', models.CharField(choices=[('recipe', 'Recipe'), ('listrecipe', 'UserListRecipe'), ('comment', 'Comment')], db_column='activity_type', max_length=12)),
                ('count', models.IntegerField(db_column='row_count')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='display_mode',
            field=models.CharField(choices=[('dark', 'Dark'), ('system', 'System'), ('light', 'Light')], default='system', max_length=6),
        ),
    ]
