# Generated by Django 3.0 on 2021-01-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0025_auto_20210108_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_welcome',
            field=models.BooleanField(default=True),
        ),
    ]
